openapi: 3.0.0
info:
  title: Photo Caption Contest API
  version: 1.0.0
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: User registered successfully
        400:
          description: Bad request
        409:
          description: Conflict, user already exists
  /login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: User logged in successfully
        400:
          description: Bad request
        401:
          description: Unauthorized, invalid credentials
  /users:
    get:
      summary: Get all users
      responses:
        200:
          description: List of all users
        401:
          description: Unauthorized
        403:
          description: Insufficient permissions
    /uuid/{uuid}:
      get:
        summary: Get user by ID
        parameters:
          - name: uuid
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: User found
          401:
            description: Unauthorized
          403:
            description: Insufficient permissions
          404:
            description: User not found
      put:
        summary: Update user by ID
        parameters:
          - name: uuid
            in: path
            required: true
            schema:
              type: string
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  email:
                    type: string
                  password:
                    type: string
        responses:
          200:
            description: User updated successfully
          401:
            description: Unauthorized
          403:
            description: Insufficient permissions
          404:
            description: User not found
      delete:
        summary: Delete user by ID
        parameters:
          - name: uuid
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: User deleted successfully
          401:
            description: Unauthorized
          403:
            description: Insufficient permissions
          404:
            description: User not found
  /photos:
    get:
      summary: Get all photos
      responses:
        200:
          description: List of all photos
        401:
          description: Unauthorized
        403:
          description: Insufficient permissions
    post:
      summary: Upload a new photo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                title:
                  type: string
      responses:
        200:
          description: Photo uploaded successfully
        401:
          description: Unauthorized
        403:
          description: Insufficient permissions
    /uuid/{uuid}:
      get:
        summary: Get photo by ID
        parameters:
          - name: uuid
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: Photo found
          401:
            description: Unauthorized
          403:
            description: Insufficient permissions
          404:
            description: Photo not found
      put:
        summary: Update photo by ID
        parameters:
          - name: uuid
            in: path
            required: true
            schema:
              type: string
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                  title:
                    type: string
        responses:
          200:
            description: Photo updated successfully
          401:
            description: Unauthorized
          403:
            description: Insufficient permissions
          404:
            description: Photo not found
      delete:
        summary: Delete photo by ID
        parameters:
          - name: uuid
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: Photo deleted successfully
          401:
            description: Unauthorized
          403:
            description: Insufficient permissions
          404:
            description: Photo not found
  /captions:
    get:
      summary: Get all captions
      responses:
        200:
          description: List of all captions
        401:
          description: Unauthorized
        403:
          description: Insufficient permissions
    post:
      summary: Upload a new caption
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photo_uuid:
                  type: string
                caption_text:
                  type: string
      responses:
        200:
          description: Caption uploaded successfully
        401:
          description: Unauthorized
        403:
          description: Insufficient permissions
    /uuid/{uuid}:
      get:
        summary: Get caption by ID
        parameters:
          - name: uuid
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: Caption found
          401:
            description: Unauthorized
          403:
            description: Insufficient permissions
          404:
            description: Caption not found
      put:
        summary: Update caption by ID
        parameters:
          - name: uuid
            in: path
            required: true
            schema:
              type: string
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  caption_text:
                    type: string
        responses:
          200:
            description: Caption updated successfully
          401:
            description: Unauthorized
          403:
            description: Insufficient permissions
          404:
            description: Caption not found
  /votes:
    post:
      summary: Create a vote for a caption
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                caption_uuid:
                  type: string
                vote_value:
                  type: integer
      responses:
        200:
          description: Vote created successfully
        401:
          description: Unauthorized
        403:
          description: Insufficient permissions
